version: '3.9'
services:
  db:
    container_name: db
    image: mysql:8.0
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - db-data:/data
    env_file:
      - docker.env

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - "8080:8080"

  redis:
    container_name: redis
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  redis-commander:
    container_name: redis-commander
    image: rediscommander/redis-commander:latest
    env_file:
      - docker.env
    ports:
      - "8081:8081"
    depends_on:
      - redis

  api:
    container_name: nestjs-rest-api
    image: nestjs-rest
    env_file:
      - docker.env
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis

volumes:
  db-data:
    driver: local
  redis-data:
    driver: local
